---
title: "STAT 385 Final Project"
author: ""
date: "Due by 12:00 PM noon CST on 05/14/2021"
output: html_document
runtime: shiny
---
Group Members:

- Kayla Winfrey: kaylarw2
- Yuchen Wang: yuchenw7
- Zihe Wu: zihewu2
- Henrik Yushin Tseng: hyt2

YouTube Video: 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(shiny)
library(shinyWidgets)

original <- read.csv("https://uofi.box.com/shared/static/9elozjsg99bgcb7gb546wlfr3r2gc9b7.csv")

# Get our dataset ready for plotting
ccso_bookings = original %>% 
    mutate(Booking.Date.Time = parse_datetime(Booking.Date.Time, format = "%m/%d/%y %H:%M:%S")) %>% 
    filter(Release.Date.Time != "1/00/00 00:00:00") %>%
    mutate(Release.Date.Time = parse_datetime(Release.Date.Time, format = "%m/%d/%y %H:%M:%S"))
```

```{r}
# Define UI for application that draws a histogram
ui <- fluidPage(
    titlePanel("Length of Time Spent in Champaign County Jails by Various Demographics"),
    
    sidebarPanel(
        
        selectInput("checkRace", 
        h4("Race"), choices = list("White" = "White", "Hispanic" = "Hispanic", "White (Hispanic)" = "White (Hispanic)", "Black" = "Black", "Asian/Pacific Islander" = "Asian/Pacific Islander", "Native American" = "Native American", "Unknown" = "Unknown"), selected = "White"),
        
        selectInput("checkMarital", 
        h4("Marital Status"), choices = list("Married" =  "Married", "Single" = "Single", "Seperated" = "Separated", "Significant Other" = "Significant Other", "Divorced" = "Divorced", "Widowed" = "Widowed", "Unknown" = "Unknown"), selected = "Married"),
        
        selectInput("checkSex", 
        h4("Sex"), choices = list("Female" = "Female", "Male" = "Male"), selected = "Female"),
        
        selectInput("checkEmployment", 
        h4("Employment"), choices = list("Employed - Full Time" = "Employed - Full Time", "Employed - Part Time" = "Employed - Part Time", "Laid Off" = "Laid Off", "Retired" = "Retired", "Self Employed" = "Self Employed", "Student" = "Student", "Unemployed" = "Unemployed")),
        
        materialSwitch("switch", label = h4("Switch to Hours"), status = "info"),
        
        width = 3
    ),
    
    mainPanel( 
        # Show a plot of the generated distribution
        plotOutput("Plot"),
        
        # Show the sample size 
        uiOutput("SampleSize")
    )
)
# Define server logic required to draw a ggplot
server <- function(input, output) {
    
    output$Plot <- renderPlot({
        dat <- ccso_bookings %>% 
            filter(RACE %in% input$checkRace) %>%
            filter(MARITIAL.STATUS %in% input$checkMarital) %>%
            filter(SEX %in% input$checkSex) %>%
            filter(EMPLOYMENT.STATUS %in% input$checkEmployment) %>%
            mutate(time.spent.in.jail = as.numeric(difftime(Release.Date.Time, Booking.Date.Time, units = ifelse(input$switch, "hours", "days")))) %>%
            select(RACE, SEX, CITY, MARITIAL.STATUS, EMPLOYMENT.STATUS, time.spent.in.jail)
        
        ggplot(data = dat) +
            geom_histogram(aes(x = time.spent.in.jail), color = "lightblue", fill = "lightblue", binwidth = 25) +
            labs(x = "Time Spent in Jail (Default: Days)", caption = "Note: the default time spent in jail is in days but the switch on the left can alter the unit into hours") + 
            theme_minimal() +
            theme(plot.caption = element_text(hjust = 0.5))
        
    })
    
    output$SampleSize <- renderTable({
        dat <- ccso_bookings %>% 
            filter(RACE %in% input$checkRace) %>%
            filter(MARITIAL.STATUS %in% input$checkMarital) %>%
            filter(SEX %in% input$checkSex) %>%
            filter(CITY %in% input$checkCity) %>%
            mutate(time.spent.in.jail = as.numeric(difftime(Release.Date.Time, Booking.Date.Time, units = ifelse(input$switch, "hours", "days")))) %>%
            select(RACE, SEX, CITY, MARITIAL.STATUS, time.spent.in.jail)
        
        data.frame("Sample" = nrow(dat))})
}
# Run the app
shinyApp(ui = ui, server = server,options = list(height = 600))
```

```{r, eval = FALSE}
# don't need this section

# histogram
graph_days_in_jail = hist(ccso_bookings_days$TimeSpentInJail, breaks = 80, xlim = c(0,300), col = "blue", main = "Days Spend in Jail", xlab = "Days", ylab = "Number of People")

# bunch of histograms
ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "White",]
histogram_white <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Hispanic",]
histogram_hispanic <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Hispanic" | ccso_bookings_days$Race == "White",]
histogram_white_hispanic <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")


ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Black",]
histogram_black <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Asian/Pacific Islander",]
histogram_asian <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Native American",]
histogram_native_american <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Race == "Unknown",]
histogram_race_unknown <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Married",]
histogram_married <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Single",]
histogram_single <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Seperated",]
histogram_seperated <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Significant Other",]
histogram_significant_other <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Divorced",]
histogram_divorced <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 1000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Widowed",]
histogram_widowed <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$MaritalStatus == "Unknown",]
histogram_marriage_unknown <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 100) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Sex == "Male",]
histogram_male <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$Sex == "Female",]
histogram_female <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 1000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$City == "CHAMPAIGN",]
histogram_champaign <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

ccso_bookings_cur <- ccso_bookings_days[ccso_bookings_days$City == "URBANA",]
histogram_urbana <- ggplot(ccso_bookings_cur, aes(x = TimeSpentInJail)) + geom_histogram(bins = 40) + xlim(0, 300) + ylim(0, 10000) + xlab("days in jail")

```
